parameters:
  image_filter:
    filters:
      post.jumbotron.primary:
        service: App\Service\Media\ImageManipulator\Filter\ResizerFilter
        arguments: { width: 1200, height: 500 }

      post.jumbotron.secondary:
        service: App\Service\Media\ImageManipulator\Filter\ResizerFilter
        arguments: { width: 800, height: 500 }

      post.jumbotron.mobile:
        service: App\Service\Media\ImageManipulator\Filter\ResizerFilter
        arguments: { width: 750, height: 500 }
