parameters:
  image_filter:
    filters:
      post.jumbotron.primary:
        service: App\Service\Media\ImageManipulator\Filter\ResizerFilter
        arguments: [ 1200, 500 ]

      post.jumbotron.secondary:
        service: App\Service\Media\ImageManipulator\Filter\ResizerFilter
        arguments: [ 800, 500 ]

      post.jumbotron.mobile:
        service: App\Service\Media\ImageManipulator\Filter\ResizerFilter
        arguments: [ 750, 400 ]
