parameters:
  media:
    directory: '%kernel.project_dir%/public'
    public_directory: 'media'
    contexts:
      default:
        providers:
          - media.provider.file
          - media.provider.image
      post:
        providers:
          - media.provider.image

    providers:
      media.provider.file: []